### ISSUE TITLE
有空把这个并了

### ISSUE THREAD

**Issue by simonsmh** [SYHGroup/easy_shell#1]
https://gist.github.com/simonsmh/ecb333f938ecd94db8b3c80f44dbf36b

**Comment by Jerry981028** [comment]
啧啧,那还不简单

**Comment by simonsmh** [comment]
并完了写个自动合并为shellbox.sh的shell

**Comment by Jerry981028** [comment]
啥

**Comment by Jerry981028** [comment]
https://github.com/SYHGroup/easyshell/tree/master/shellbox

**Comment by simonsmh** [comment]
。。啧啧，拆开来放独立shell
算了我自己来吧
